---
title: "Homework 6"
author: "Alexis Colangelo"
date: "11/17/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)


knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

  options(
    ggplot2.continuous.colour = "viridis",
    ggplot2.continuous.fill = "viridis"
  )
  
  scale_colour_discrete = scale_colour_viridis_d
  scale_fill_discrete = scale_fill_viridis_d
  
  theme_set(theme_minimal() + theme(legend.position = "bottom"))
  
```

## Problem 1

Load and clean the data for regression analysis (i.e. convert numeric to factor where appropriate, check for missing data, etc.).

```{r}
birthweight_data = read_csv(file = "./data/birthweight.csv") %>%
  mutate(
    babysex = 
      recode(babysex, "1" = "male", "2" = "female"),
      babysex = factor(babysex),
    frace = 
      recode(frace, "1" = "white", "2" = "black", 
             "3" = "asian", "4" = "puerto_rican", 
             "8" = "other", "9" = "unknown"),
      frace = factor(frace),
    malform = 
      recode(malform, "0" = "absent", "1" = "present"),
      malform = factor(malform),
    mrace =
      recode(mrace, "1" = "white", "2" = "black",
             "3" = "asian", "4" = "puerto_rican",
             "8" = "other"),
      mrace = factor(mrace)
  ) %>% view()
```


